### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by SchulteMarkus** [cloudstark/quarkus-zalando-problem-extension#25]
This project is licensed under the Apache license 2.0, see [LICENSE](LICENSE).
Though, in some files there is 
```
/*
 *    Copyright 2020 SMB GmbH
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
```

I am pretty sure a project under the APL2.0 cannot have restrictions regarding the copyright.

If the project is under APL2.0, there should only be the [LICENSE](LICENSE), and maybe the "license"-info in the [pom.xml](pom.xml). I suggest to remove every other copyright/copyleft note (in special, from Java source files).

**Comment by CrystalMethod** [comment]
Thanks for you thoughts on this topic. If you look at https://github.com/cloudstark/quarkus-zalando-problem-extension/blob/master/LICENSE#L178 you can read how to apply the license. This is a common practice you can see if you look at a random repository on Github. Copyright and license are two different things. As the author (german: Urheber) of some source code I always own the copyright (german: Urheberrecht) - no matter under which license the source code get published afterwards. 

How about this extended statement:  "Copyright 2020 SMB GmbH and contributors."
And of course we can also add the `developers` tag to the [pom.xml](https://github.com/cloudstark/quarkus-zalando-problem-extension/blob/master/pom.xml)

This leads us to the next task: provide a "contribution" guideline.

**Comment by SchulteMarkus** [comment]
Thanks for the feedback, I learned something new!
My point of view: issue resolved, no change needed.

**Comment by CrystalMethod** [comment]
A final thought because I just noticed this on https://github.com/cloudstark/quarkus-zalando-problem-extension/blob/master/LICENSE On top of the license page Github has added some thoughts and usage guidelines of the selected license (Apache 2.0 in our case).
