### ISSUE TITLE
Enable "causal chains"

### ISSUE THREAD

**Issue by SchulteMarkus** [cloudstark/quarkus-zalando-problem-extension#34]
Zalando problem supports "causal chains" as described on https://github.com/zalando/problem#stack-traces-and-causal-chains.

```json
{
  "type": "https://example.org/order-failed",
  "title": "Order failed",
  "status": 400,
  "cause": {
    "type": "https://example.org/out-of-stock",
    "title": "Out of Stock",
    "status": 400,
    "detail": "Item B00027Y5QG is no longer available"
  }
}
```

**Feature request**
The cause for a "problem" is given as part of a Quarkus "problem" response, too.

**Comment by CrystalMethod** [comment]
This ist already supported and we are already using it. But it is not covered yet by any test. Have a look at https://github.com/cloudstark/quarkus-zalando-problem-extension/blob/master/runtime/src/main/java/solutions/cloudstark/quarkus/zalando/problem/runtime/jsonb/DefaultProblemSerializer.java#L50-L52

**Comment by SchulteMarkus** [comment]
Ah, I see  - if a problem had a "cause", it was "rendered" already.
#41 adds the ability, if an exception has a cause, that this cause will be "rendered", too.
